{% set name = "google-cloud-translate" %}
{% set version = "3.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd0af6aa1a5429e15a1af7a912b0ddd174b078aa79577659adc65628be9a0cf4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - google-cloud-core >=1.4.4,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.translate
    - google.cloud.translate_v2
    - google.cloud.translate_v3beta1
    - google.cloud.translate_v3
    - grpc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-translate
  summary: Google Cloud Translate API client library
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://googleapis.dev/python/translation/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-translate

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
    - xylar
