schema_version: 1

context:
  name: google-cloud-translate
  version: "3.24.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_cloud_translate-${{ version }}.tar.gz
  sha256: 2f3b8b90f8cdaf63a435d18e63b21c3650de31fc4f858623f2d0d69be0cd3e9a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    # excluding python 3.14 for now because we don't have the required grpcio on conda-forge
    - python >=${{ python_min }},<3.14
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    - google-cloud-core >=1.4.4,<3.0.0
    # using looser constraint because we can't support the python >=3.14 constraint
    - grpcio >=1.33.2,<2.0.0
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.14.0,<1.0.0

tests:
  - python:
      imports:
        - google.cloud.translate
        - google.cloud.translate_v2
        - google.cloud.translate_v3beta1
        - google.cloud.translate_v3
        - grpc
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Google Cloud Translate API client library
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-translate
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-translate
  documentation: https://googleapis.dev/python/translation/latest/index.html

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
    - xylar
